// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace Mirai_GameWiki.Model.Mysql
{
    public partial class qqbotContext : DbContext
    {
        public qqbotContext()
        {
        }

        public qqbotContext(DbContextOptions<qqbotContext> options)
            : base(options)
        {
        }

        public virtual DbSet<users> users { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasCharSet("utf8mb4")
                .UseCollation("utf8mb4_bin");

            modelBuilder.Entity<users>(entity =>
            {
                entity.Property(e => e.Id).HasComment("主键");

                entity.Property(e => e.uname).HasComment("用户名");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}